
let testData = {
  farm: {
    id_number: 'Some Stuff here',
    country: 'Some Stuff here',
    address: 'Some Stuff here',
    zip: 'Some Stuff here',
    town: 'Some Stuff here',
    visit_date_arranged: '10.08.2021',
    visit_date_actual: '18.09.2021',
  },
  preVisit: {
    herd_size: 50,
    sample_size: 45,
    nr_groups: 8,
  },
  managementQuestionnaire: {
    temp_in: 20,
    temp_out: 15,
    pasture_access: true,
    pasture_days_year: 0,
    pasture_hours_day: 0,
    pasture_days_comment: true,
    outdoor_access: true,
    outdoor_days_year: 0,
    outdoor_hours_day: 0,
    loose_housed: true,
    nr_dystocia_12_mos: 2,
    nr_downercows_12_mos: 2,
    nr_mortality_12_mos: 2,
    disb_deho_on_farm: 2,
    disb_deho_method: 2,
    hot_air: 9999,
    disb_deho_anaesthesia: 2,
    disb_deho_analgesia: 2,
    td_on_farm: 2,
    td_method: 2,
    td_anaesthesia: 2,
    td_analgesia: 2,
    calf_mother_time: 2,
    singlebox_time: 2,
    milk_volume_daily: 2,
    colostrum_volume: 2,
    concentrate_age: 2,
    roughage_age: 2,
    water_age: 2,
    fav_cow: 0,
    special_measure: 0,
    special_measure_desc: 'Some texts',
    nr_milkrec_3mos: 14,
    pct_scc400k_3mos: 2,
    avg_dairy_cow_12mos: 4,
    avg_calvings_year: 3,
  },
  qualitativeBehaviorAnalysis: {
    active: 110,
    relaxed: 110,
    fearful: 110,
    agitated: 110,
    calm: 110,
    content: 110,
    indifferent: 110,
    frustrated: 110,
    friendly: 110,
    bored: 110,
    playful: 110,
    positively_occupied: 110,
    lively: 110,
    inquisitive: 110,
    irritable: 110,
    calmless_uneasy: 110,
    sociable: 110,
    apathetic: 110,
    happy: 110,
    distressed: 110,
  },
  testGroups: [
    {
      group_name: 'Heffalo',
      group_size: 21,
      group_sample: 11,
    },
  ],
  resources: [{ group_name: 'Heffalo', nr_wps: 1 }],
  waterPoints: [
    {
      group_name: 'Heffalo',
      nr_animals_using_wps: 2,
      type: 2,
      troughlength: 100,
      cleanliness: 1,
      functioning: 'Functioning',
      waterflow: 'Adequate',
    },
  ],
  lyingTimeAndCollision: [{ lie_t: 2.5, collision: 'Present' }],
  socialBehaviorAndCoughing: [
    {
      segment: 'Segment 1',
      group_name: 'Heffalo',
      start: '12:15',
      finish: '12:30',
      standing_start: 1,
      standing_finish: 1,
      eat_drink_start: 1,
      eat_drink_finish: 1,
      lying_start: 1,
      lying_finish: 1,
      sum_start: 3,
      sum_finish: 3,
      lying_out_start: 1,
      lying_out_finish: 1,
      duration: 15,
      headbutt: 1,
      displacement: 1,
      fighting: 1,
      chasing: 1,
      chasing_up: 1,
      coughing: 1,
    },
  ],
  avoidanceDistanceTesting: [
    {
      group_name: 'Heffalo',
      ear_tag: '1234',
      side: 'Right',
      a_d_t1: 70,
      a_d_t2: undefined,
      nasal_discharge: 'Present',
      ocular_discharge: 'Abscent',
      comment: 'Some adt comment',
    },
  ],
  clinicalScoring: [
    {
      group_name: 'Heffalo',
      ear_tag: null,
      side: 'Right',
      breed: 2,
      bcs_wq: 0,
      bcs_std: 4.5,
      clean_scr_lower_hindleg: 1,
      clean_scr_upper_hindleg: 1,
      clean_scr_udderwq: 1,
      clean_scr_udder: 0,
      clean_scr_teats: 0,
      integ_tarsus: 0,
      nr_hairless_tarsus: 0,
      nr_lesion_tarsus: 0,
      nr_swelling_tarsus: 0,
      integ_hindquarter: 0,
      nr_hairless_hq: 0,
      nr_lesion_hq: 0,
      nr_swelling_hq: 0,
      integ_neck_shoulder_back: 0,
      nr_hairless_nsb: 0,
      nr_lesion_nsb: 0,
      nr_swelling_nsb: 0,
      integ_carpus: 0,
      nr_hairless_carpus: 0,
      nr_lesion_carpus: 0,
      nr_swelling_carpus: 0,
      integ_flank_side_udder: 0,
      nr_hairless_fsu: 0,
      nr_lesion_fsu: 0,
      nr_swelling_fsu: 0,
      integ_other: 0,
      integ_other_specify: 'Specification Integ',
      tail_broken: 0,
      hampered_respiration: 0,
      diarrhoea: 0,
      vulval_discharge: 0,
      lameness: 0,
      comment: 'Some interesting comment',
    },
  ],
}

testData = {
  farm: {
    id_number: 'Some Stuff here',
    country: 'Some Stuff here',
    address: 'Some Stuff here',
    zip: 'Some Stuff here',
    town: 'Some Stuff here',
    visit_date_arranged: '10.08.2021',
    visit_date_actual: '18.09.2021',
  },
  preVisit: {
    herd_size: 50,
    sample_size: 45,
    nr_groups: 8,
  },
  managementQuestionnaire: {
    temp_in: 20,
    temp_out: 15,
    pasture_access: true,
    pasture_days_year: 0,
    pasture_hours_day: 0,
    pasture_days_comment: 'Some comment',
    outdoor_access: true,
    outdoor_days_year: 0,
    outdoor_hours_day: 0,
    loose_housed: true,
    nr_dystocia_12_mos: 2,
    nr_downercows_12_mos: 2,
    nr_mortality_12_mos: 2,
    disb_deho_on_farm: 2,
    disb_deho_method: 2,
    hot_air: 9999,
    disb_deho_anaesthesia: 2,
    disb_deho_analgesia: 2,
    td_on_farm: 2,
    td_method: 2,
    td_anaesthesia: 2,
    td_analgesia: 2,
    calf_mother_time: 2,
    singlebox_time: 2,
    milk_volume_daily: 2,
    colostrum_volume: 2,
    concentrate_age: 2,
    roughage_age: 2,
    water_age: 2,
    fav_cow: false,
    special_measure: true,
    special_measure_desc: 'Some texts',
    nr_milkrec_3mos: 14,
    pct_scc400k_3mos: 2,
    avg_dairy_cow_12mos: 4,
    avg_calvings_year: 4,
  },
  qualitativeBehaviorAnalysis: {
    active: 110,
    relaxed: 110,
    fearful: 110,
    agitated: 110,
    calm: 110,
    content: 110,
    indifferent: 110,
    frustrated: 110,
    friendly: 110,
    bored: 110,
    playful: 110,
    positively_occupied: 110,
    lively: 110,
    inquisitive: 110,
    irritable: 110,
    calmless_uneasy: 110,
    sociable: 110,
    apathetic: 110,
    happy: 110,
    distressed: 110,
  },
  testGroups: Array(15)
    .fill(0)
    .map((i) => ({
      group_name: 'Heffalo',
      group_size: 21,
      group_sample: 11,
    })),
  resources: Array(15)
    .fill(0)
    .map((i) => ({ group_name: 'Heffalo', nr_wps: 1 })),
  waterPoints: Array(30)
    .fill(0)
    .map((i) => ({
      group_name: 'Heffalo',
      nr_animals_using_wps: 2,
      type: 2,
      troughlength: 100,
      cleanliness: 1,
      functioning: 'Functioning',
      waterflow: 'Adequate',
    })),
  lyingTimeAndCollision: Array(30)
    .fill(0)
    .map((i) => ({ lie_t: 2.5, collision: 'Present' })),
  socialBehaviorAndCoughing: Array(60)
    .fill(0)
    .map((i) => ({
      segment: 'Segment 1',
      group_name: 'Heffalo',
      start: '12:15',
      finish: '12:30',
      standing_start: 1,
      standing_finish: 1,
      eat_drink_start: 1,
      eat_drink_finish: 1,
      lying_start: 1,
      lying_finish: 1,
      sum_start: 3,
      sum_finish: 3,
      lying_out_start: 1,
      lying_out_finish: 1,
      duration: 15,
      headbutt: 1,
      displacement: 1,
      fighting: 1,
      chasing: 1,
      chasing_up: 1,
      coughing: 1,
    })),
  avoidanceDistanceTesting: Array(150)
    .fill(0)
    .map((i) => ({
      group_name: 'Heffalo',
      ear_tag: '1234',
      side: 'Right',
      a_d_t1: 70,
      a_d_t2: undefined,
      nasal_discharge: 'Present',
      ocular_discharge: 'Abscent',
      comment: 'Some adt comment',
    })),
  clinicalScoring: Array(150)
    .fill(0)
    .map((i) => ({
      group_name: 'Heffalo',
      ear_tag: '100',
      side: 'Right',
      breed: 2,
      bcs_wq: 0,
      bcs_std: 4.5,
      clean_scr_lower_hindleg: 1,
      clean_scr_upper_hindleg: 1,
      clean_scr_udderwq: 1,
      clean_scr_udder: 0,
      clean_scr_teats: 0,
      integ_tarsus: 0,
      nr_hairless_tarsus: 0,
      nr_lesion_tarsus: 0,
      nr_swelling_tarsus: 0,
      integ_hindquarter: 0,
      nr_hairless_hq: 0,
      nr_lesion_hq: 0,
      nr_swelling_hq: 0,
      integ_neck_shoulder_back: 0,
      nr_hairless_nsb: 0,
      nr_lesion_nsb: 0,
      nr_swelling_nsb: 0,
      integ_carpus: 0,
      nr_hairless_carpus: 0,
      nr_lesion_carpus: 0,
      nr_swelling_carpus: 0,
      integ_flank_side_udder: 0,
      nr_hairless_fsu: 0,
      nr_lesion_fsu: 0,
      nr_swelling_fsu: 0,
      integ_other: 0,
      integ_other_specify: 'Specification Integ',
      tail_broken: 0,
      hampered_respiration: 0,
      diarrhoea: 0,
      vulval_discharge: 0,
      lameness: 0,
      comment: 'Some interesting comment',
    })),
}

export default testData
